// Generated wrapper metadata is committed so package installation never needs
// to execute a target binary, which also keeps cross-compilation straightforward.

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let wrapper_path = "../R/extendr-wrappers.R";
    let header = "\
        # Generated by extendr: Do not edit by hand\n\
        # nolint start\n\
        \n\
        #' @usage NULL\n\
        #' @useDynLib panache, .registration = TRUE\n\
        NULL\n\
        \n\
    ";
    let footer = "# nolint end\n";
    let wrappers = panache::get_panache_metadata()
        .make_r_wrappers(true, "panache")
        .map_err(|error| format!("failed to generate wrappers: {error}"))?;
    std::fs::write(wrapper_path, format!("{header}{wrappers}{footer}"))
        .map_err(|error| format!("failed to write {wrapper_path}: {error}"))?;
    Ok(())
}
